PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
# More readable version of datasets
SELECT  distinct ?uri ?D_title  ?D_description ?D_creator_identifier ?D_creator_name  ?D_accrualPeriodicity ?D_identifier ?D_issued ?D_keyword ?D_theme  ?D_modified  ?D_publisher_identifier ?D_publisher_name ?D_rightsHolder_identifier ?D_rightsHolder_name  ?D_contactPoint_fn ?D_contactPoint_hasEmail_nonorm ?D_distribution ?D_landingPage ?Dist_description
   ?Dist_format ?Dist_license ?Dist_title ?Dist_accessURL WHERE {
  ?uri a dcat:Dataset .
  optional {?uri  dct:title ?D_title} .
  optional {?uri dct:description ?D_description} .
  optional {?uri dct:creator ?D_creator. 
    			?D_creator  dct:identifier ?D_creator_identifier ;
                 foaf:name ?D_creator_name .} 
  optional { ?uri dct:accrualPeriodicity ?D_accrualPeriodicity }.
  optional {?uri dct:identifier ?D_identifier }.
  optional {?uri  dct:issued ?D_issued}.
  optional {?uri dcat:keyword ?D_keyword} .
  optional {?uri dcat:theme ?D_theme }.
  optional {?uri dct:modified ?D_modified }.
  optional {?uri dct:publisher  ?D_publisher .
                 ?D_publisher  dct:identifier ?D_publisher_identifier ;
    				foaf:name ?D_publisher_name }.
  optional {?uri dct:rightsHolder ?D_rightsHolder .
     			?D_rightsHolder  dct:identifier ?D_rightsHolder_identifier ;
                     foaf:name ?D_rightsHolder_name . }
  optional {?uri dct:spatial ?D_spatial }.
  optional {?uri dct:language  ?D_language }.
  optional {?uri dcat:contactPoint ?D_contactPoint .
        ?D_contactPoint vcard:fn ?D_contactPoint_fn . 
        ?D_contactPoint  vcard:hasEmail ?D_contactPoint_hasEmail_nonorm }.
   optional{  ?uri dcat:distribution ?D_distribution. 
     ?D_distribution a    dcat:Distribution ;
    dct:description ?Dist_description;
    dct:format ?Dist_format ;
    dct:license ?Dist_license ;
    dct:title ?Dist_title ;
    dcat:accessURL ?Dist_accessURL }.
   ?uri dcat:landingPage ?D_landingPage ;
   
}